Search.setIndex({
  docnames: ['framework', 'index', 'map', 'template'],
  envversion: {
    'sphinx.domains.c': 2,
    'sphinx.domains.changeset': 1,
    'sphinx.domains.citation': 1,
    'sphinx.domains.cpp': 4,
    'sphinx.domains.index': 1,
    'sphinx.domains.javascript': 2,
    'sphinx.domains.math': 2,
    'sphinx.domains.python': 3,
    'sphinx.domains.rst': 2,
    'sphinx.domains.std': 2,
    'sphinx': 56,
  },
  filenames: ['framework.md', 'index.md', 'map.md', 'template.md'],
  objects: {},
  objnames: {},
  objtypes: {},
  terms: {
    '0': 2,
    '00': 2,
    '000z': 2,
    '03': [2, 3],
    '04514': 2,
    '05': 3,
    '06': 2,
    '07': 2,
    '1': [2, 3],
    '1035cd306a2f85b362b1a20ce315b8eb': 3,
    '118': 2,
    '15': 2,
    '18': 2,
    '18t00': 2,
    '2016': 2,
    '2017': 2,
    '2018': 1,
    '2020': 2,
    '2022': [1, 3],
    '23': 2,
    '3': 2,
    '3000': [0, 3],
    '304107484': 2,
    '306799': 2,
    '33': 2,
    '4': [],
    '5': [2, 3],
    '6': 2,
    '62nd': 2,
    '7': 2,
    '8': [2, 3],
    '9': 2,
    '983265': 2,
    '9904336958': 2,
    'class': [2, 3],
    'default': [2, 3],
    'do': [0, 2, 3],
    'final': [2, 3],
    'function': 2,
    'import': [0, 2],
    'new': [1, 2, 3],
    'null': 2,
    'public': 3,
    'return': [2, 3],
    'true': 2,
    'try': [2, 3],
    'var': 2,
    'while': [0, 2, 3],
    'A': [1, 2],
    'And': [2, 3],
    'As': [2, 3],
    'At': 2,
    'But': 2,
    'By': [2, 3],
    'For': 3,
    'If': [2, 3],
    'In': [2, 3],
    'It': [1, 2, 3],
    'Its': 2,
    'One': [2, 3],
    'That': 3,
    'The': [0, 2, 3],
    'Then': [2, 3],
    'There': 0,
    'To': [2, 3],
    '_chart': 2,
    '_data': 2,
    '_layout': [2, 3],
    '_map': 2,
    '_modul': 2,
    '_script': 2,
    '_style': 2,
    'about': [0, 2, 3],
    'abov': [2, 3],
    'accept': 3,
    'access_token': 2,
    'accord': 2,
    'account': 3,
    'across': 2,
    'act': 3,
    'activ': 2,
    'ad': [2, 3],
    'add': [2, 3],
    'addto': 2,
    'african': 2,
    'after': [2, 3],
    'ag': 2,
    'again': [2, 3],
    'aim': 0,
    'all': [0, 2, 3],
    'allow': 3,
    'almost': 0,
    'alreadi': 2,
    'alright': 2,
    'also': [2, 3],
    'america': 1,
    'american': 2,
    'amiher': 1,
    'an': [2, 3],
    'angel': [0, 2],
    'anoth': [],
    'anyon': 0,
    'anyth': 2,
    'apart': 2,
    'api': 2,
    'app': [0, 2],
    'appear': [2, 3],
    'applic': [1, 2],
    'approach': 3,
    'ar': [0, 2, 3],
    'area': 2,
    'argument': 2,
    'armand': [1, 2],
    'around': 2,
    'artist': [2, 3],
    'ask': 3,
    'assist': 1,
    'associ': 2,
    'automat': 3,
    'avail': 2,
    'avoid': 3,
    'awai': 2,
    'back': [2, 3],
    'baker': [0, 3],
    'barber': 2,
    'base': [2, 3],
    'basic': 3,
    'becaus': 3,
    'been': [0, 2, 3],
    'befor': 2,
    'believ': 0,
    'below': 3,
    'ben': 1,
    'bindtooltip': 2,
    'bl': 3,
    'black': 2,
    'blank': 2,
    'block': [2, 3],
    'bluprint': 0,
    'bodi': 3,
    'boilerpl': 3,
    'bootstrap': 2,
    'bootstrapcdn': [],
    'border': 2,
    'bother': 3,
    'bottom': 2,
    'boulevard': 2,
    'box': 2,
    'branch': 3,
    'bring': 2,
    'browser': 0,
    'browsersync': [],
    'busi': 2,
    'bylin': [2, 3],
    'call': [2, 3],
    'can': [0, 2, 3],
    'car': 2,
    'card': [1, 3],
    'case_numb': 2,
    'challeng': 0,
    'chang': [2, 3],
    'chapter': [0, 3],
    'charact': 3,
    'charset': 3,
    'chart': [1, 2],
    'chatter': 2,
    'chicago': 1,
    'choic': 0,
    'circl': 2,
    'circlemark': 2,
    'clearfix': 2,
    'click': 2,
    'clone': 0,
    'close': [2, 3],
    'cm': [],
    'code': [2, 3],
    'color': [2, 3],
    'com': [0, 2, 3],
    'combat': 2,
    'comfort': 2,
    'command': 3,
    'commit': [2, 3],
    'common': 3,
    'complet': 3,
    'complic': 3,
    'comput': [0, 1, 3],
    'confer': 1,
    'config': 3,
    'configur': 3,
    'confin': 3,
    'congratul': [0, 2, 3],
    'consol': 2,
    'content': [0, 2, 3],
    'control': 2,
    'cookbook': [],
    'coordin': 2,
    'copi': [2, 3],
    'core': 2,
    'corner': 2,
    'counti': 2,
    'coupl': 2,
    'creat': [0, 2, 3],
    'creatur': 2,
    'css': [1, 2, 3],
    'curat': 0,
    'current': 3,
    'custom': [0, 1, 2, 3],
    'd': 3,
    'dailygraph': 0,
    'dana': 1,
    'data': [0, 1, 2],
    'datadesk': 0,
    'dataset': 1,
    'date': 3,
    'datetim': [2, 3],
    'deadli': 2,
    'deadliest': 2,
    'deadlin': 1,
    'death_dat': 2,
    'death_year': 2,
    'defus': 2,
    'delet': 3,
    'demonstr': 0,
    'depend': 0,
    'deploi': 1,
    'design': 3,
    'despit': 2,
    'detail': 0,
    'develop': [0, 1, 3],
    'devic': 3,
    'di': 2,
    'dicat': 3,
    'did': 2,
    'differ': 0,
    'directori': [0, 2, 3],
    'dist': 2,
    'distanc': 2,
    'div': [2, 3],
    'django': [0, 3],
    'doctyp': 3,
    'doe': 2,
    'doesn': 3,
    'done': 3,
    'dot': 2,
    'down': 2,
    'downward': 2,
    'dozen': 0,
    'draw': 2,
    'duplic': 3,
    'e64d1f': 2,
    'each': [0, 2],
    'earlier': 3,
    'easier': 0,
    'easili': 0,
    'eddi': 2,
    'edit': 2,
    'effect': 3,
    'element': [2, 3],
    'email': 3,
    'emamdjomeh': 1,
    'emploi': 0,
    'en': 3,
    'endblock': [2, 3],
    'entri': 2,
    'escap': 1,
    'especi': 2,
    'even': [0, 3],
    'everi': [1, 2],
    'everyth': [0, 2, 3],
    'exampl': [0, 3],
    'expect': 3,
    'experi': 1,
    'extend': [2, 3],
    'extens': 2,
    'eyj1ijoibgf0aw1lcyisimeioijjanjmnjg4zzywegtvndnxa2zpz2lma3z4in0': 2,
    'fals': 2,
    'fanci': 0,
    'far': 2,
    'favor': 2,
    'featur': [2, 3],
    'feel': 2,
    'few': [],
    'file': [2, 3],
    'fill': [2, 3],
    'find': [2, 3],
    'finish': 2,
    'first': [0, 2, 3],
    'first_nam': 2,
    'firstgraph': 2,
    'flag': 3,
    'focu': 2,
    'focus': 2,
    'folder': 2,
    'follow': [0, 2, 3],
    'font': 3,
    'footer': 3,
    'foreach': 2,
    'found': [2, 3],
    'four': 2,
    'framework': [1, 3],
    'free': 0,
    'friend': 2,
    'from': [0, 1, 2, 3],
    'fun': 2,
    'fundament': 0,
    'furnitur': 3,
    'g0lyvies9y5qcuohxactha': 2,
    'gender': 2,
    'gener': [0, 2],
    'get': [0, 1, 2, 3],
    'git': [0, 1, 2, 3],
    'github': [0, 2, 3],
    'give': 2,
    'global': 3,
    'go': [0, 2, 3],
    'good': [0, 3],
    'googl': 2,
    'got': [0, 2],
    'graphic': [0, 1, 2, 3],
    'grappl': 2,
    'greater': 2,
    'guid': 1,
    'gulp': [],
    'h1': 3,
    'h3': 2,
    'ha': [2, 3],
    'half': 2,
    'hand': 1,
    'handiwork': 3,
    'handl': 2,
    'harvard': 2,
    'harvard_park_homicid': 2,
    'have': [0, 2, 3],
    'head': 3,
    'header': 3,
    'headlin': [2, 3],
    'heard': 0,
    'hei': 2,
    'hello': 3,
    'here': [2, 3],
    'highest': 2,
    'hold': 2,
    'holder': 2,
    'home': 2,
    'homepag': [],
    'homicid': 2,
    'host': 3,
    'how': [0, 1, 2, 3],
    'href': [2, 3],
    'html': [1, 2, 3],
    'http': [2, 3],
    'id': 2,
    'imag': 2,
    'img': 3,
    'immedi': 3,
    'includ': [0, 2, 3],
    'index': 2,
    'inherit': 3,
    'initi': 3,
    'inlin': 2,
    'input': 3,
    'inset': 2,
    'insid': [0, 3],
    'instal': [2, 3],
    'instanc': 3,
    'instantli': 3,
    'institut': 1,
    'instruct': 3,
    'interact': [1, 2],
    'internet': 1,
    'intersect': 2,
    'introduc': [2, 3],
    'introductori': 2,
    'invent': 3,
    'ir': 3,
    'its': [0, 2, 3],
    'javascript': [0, 1, 2],
    'jinja': 3,
    'job': 0,
    'journalist': 1,
    'jqueri': 2,
    'js': [0, 1, 2],
    'json': 2,
    'just': [2, 3],
    'keep': [],
    'kill': 2,
    'know': 2,
    'known': 0,
    'l': 2,
    'la': 2,
    'label': 2,
    'lang': 3,
    'languag': [0, 3],
    'laptop': 2,
    'larg': 3,
    'last': [0, 2],
    'last_nam': 2,
    'latim': 2,
    'latitud': 2,
    'layer': 2,
    'layout': 3,
    'lead': 2,
    'leaflet': 2,
    'learn': 3,
    'least': 2,
    'less': 2,
    'let': [2, 3],
    'level': [2, 3],
    'librari': 2,
    'life': 2,
    'like': [0, 2, 3],
    'line': 3,
    'link': [2, 3],
    'lino': 2,
    'list': 2,
    'live': 2,
    'll': [2, 3],
    'lo': [0, 2],
    'load': 2,
    'local': 3,
    'localhost': [0, 3],
    'log': [2, 3],
    'logic': 2,
    'logo': 3,
    'longitud': 2,
    'look': [2, 3],
    'lot': 0,
    'lucki': 2,
    'm': [2, 3],
    'made': [0, 2, 3],
    'mai': 3,
    'main': [2, 3],
    'maintain': 3,
    'make': [0, 1, 2, 3],
    'male': 2,
    'manag': [0, 1, 3],
    'mani': 0,
    'map': 1,
    'mapbox': 2,
    'mar': [2, 3],
    'martinez': 1,
    'master': 2,
    'match': 2,
    'maxcdn': [],
    'maxzoom': 2,
    'mayb': 0,
    'md': [],
    'me': [2, 3],
    'men': 2,
    'meta': 3,
    'method': 2,
    'middle_nam': 2,
    'might': [2, 3],
    'min': [],
    'mini': 2,
    'minimap': 2,
    'minzoom': 2,
    'mix': 3,
    'modul': 2,
    'more': [0, 2, 3],
    'most': [0, 2, 3],
    'mous': 2,
    'move': [2, 3],
    'mozilla': 3,
    'much': 3,
    'my': 3,
    'name': [0, 2, 3],
    'nation': 1,
    'nav': 3,
    'navig': [],
    'necessari': 0,
    'need': [0, 2, 3],
    'neighborhood': 2,
    'newsapp': 0,
    'newsroom': [0, 3],
    'next': [2, 3],
    'nicar': 1,
    'node': [0, 1],
    'node_modul': 2,
    'nor': 3,
    'normal': 2,
    'note': [],
    'noth': 0,
    'notic': 3,
    'now': [0, 2, 3],
    'npm': [0, 2],
    'npr': 0,
    'number': 2,
    'nunjuck': [2, 3],
    'obj': 2,
    'ock': 3,
    'off': 2,
    'offer': 0,
    'often': 2,
    'okai': 2,
    'onc': [0, 3],
    'one': [2, 3],
    'ones': 3,
    'onlin': [],
    'opac': 2,
    'open': [0, 3],
    'openstreetmap': 2,
    'option': 2,
    'orang': 2,
    'org': 3,
    'organ': [0, 1, 3],
    'origin': [2, 3],
    'other': [0, 2, 3],
    'our': [2, 3],
    'out': [0, 3],
    'overal': 0,
    'own': [0, 3],
    'p': [2, 3],
    'packag': [0, 3],
    'page': [0, 2, 3],
    'palewir': [0, 1, 2, 3],
    'paragraph': [2, 3],
    'parallel': 3,
    'parent': 3,
    'park': 2,
    'parlanc': 3,
    'particular': 0,
    'past': [2, 3],
    'path': [2, 3],
    'paus': 3,
    'peer': 0,
    'peopl': 2,
    'perman': 2,
    'piec': 2,
    'pk': 2,
    'place': 2,
    'placehold': [2, 3],
    'png': 3,
    'point': [0, 2],
    'politico': 0,
    'popular': 0,
    'popup': 2,
    'posit': 0,
    'post': [0, 1, 2, 3],
    'prefac': 2,
    'prepar': 1,
    'prerequisit': 1,
    'preview': 0,
    'principl': 0,
    'print': 3,
    'probabl': 3,
    'problem': 2,
    'process': 1,
    'program': 0,
    'project': 0,
    'prompt': 3,
    'provid': [2, 3],
    'pubdat': [2, 3],
    'publish': [0, 1],
    'pull': 0,
    'push': [2, 3],
    'put': 2,
    'python': [0, 3],
    'quickli': 3,
    'race': 2,
    'rail': 0,
    'rather': 3,
    'raw': 3,
    're': [0, 2],
    'react': 0,
    'reader': 2,
    'readi': [0, 2],
    'readm': [],
    'readthedoc': [],
    'real': [2, 3],
    'record': 2,
    'regener': 2,
    'reinvent': 3,
    'rel': 3,
    'releas': 0,
    'reli': 2,
    'reload': [2, 3],
    'reloc': 2,
    'remaind': 0,
    'remot': 3,
    'replac': 3,
    'report': [1, 2, 3],
    'repositori': [0, 3],
    'requir': [0, 3],
    'respositori': 3,
    'restrict': 2,
    'reus': 0,
    'reuter': 0,
    'rev': 3,
    'revis': 1,
    'right': 2,
    'rigid': 1,
    'rippl': 3,
    'road': 2,
    'root': 3,
    'rosendo': 2,
    'rubi': 0,
    'run': [0, 3],
    'runtim': 2,
    's': [0, 1, 2, 3],
    'same': [0, 3],
    'sat2': 2,
    'sat': 2,
    'satellit': 2,
    'save': [0, 2, 3],
    'scale': 3,
    'scheme': 3,
    'script': [2, 3],
    'scroll': 2,
    'scrollwheelzoom': 2,
    'scss': 2,
    'seattl': 0,
    'second': 3,
    'section': 2,
    'see': [0, 2, 3],
    'send': 3,
    'session': 1,
    'set': [0, 2, 3],
    'setview': 2,
    'share': [0, 2, 3],
    'shop': 2,
    'shortcut': 3,
    'should': [2, 3],
    'show': [1, 2, 3],
    'similar': 3,
    'simpelifi': [],
    'simpl': [2, 3],
    'simplifi': [0, 3],
    'sit': 2,
    'site': [0, 2, 3],
    'six': 2,
    'slug': 2,
    'small': [2, 3],
    'so': [2, 3],
    'softwar': 0,
    'some': [0, 2, 3],
    'someth': 3,
    'sometim': 3,
    'sophist': 3,
    'sourc': 0,
    'south': 2,
    'southwest': 2,
    'specif': 0,
    'sprinkl': 2,
    'src': [2, 3],
    'stage': 1,
    'stand': [0, 2, 3],
    'standalon': 1,
    'standard': 3,
    'start': [2, 3],
    'state': 3,
    'statu': 3,
    'step': [1, 2, 3],
    'stick': 3,
    'stop': 1,
    'store': 2,
    'stori': 3,
    'street': 2,
    'strict': 2,
    'stroke': 2,
    'strong': 2,
    'style': [2, 3],
    'stylesheet': [2, 3],
    'summari': 3,
    'syncron': 3,
    'system': [1, 3],
    't': [1, 2, 3],
    'tag': [2, 3],
    'take': [0, 3],
    'talk': [0, 1, 2, 3],
    'team': 0,
    'templat': [0, 1, 2],
    'tend': 0,
    'termin': [0, 2],
    'test': 3,
    'texa': 0,
    'than': [0, 2, 3],
    'thank': 3,
    'thei': [0, 2, 3],
    'them': [0, 2, 3],
    'themselv': [],
    'thi': [0, 1, 2, 3],
    'thing': 2,
    'those': 2,
    'three': 2,
    'through': 2,
    'tighten': 2,
    'tile': 2,
    'tilelay': 2,
    'time': [0, 2, 3],
    'titl': 3,
    'togeth': 0,
    'too': [2, 3],
    'tool': [0, 2, 3],
    'tooltip': 2,
    'top': [1, 3],
    'total': 2,
    'track': 3,
    'trackpad': 2,
    'train': 1,
    'trend': 2,
    'tribun': 0,
    'trick': 0,
    'trigger': 2,
    'turn': 2,
    'tutori': [0, 1, 2, 3],
    'two': 3,
    'typic': 3,
    'underli': 0,
    'until': [1, 2],
    'up': [0, 2, 3],
    'updat': 3,
    'us': [0, 2, 3],
    'user': 3,
    'utf': 3,
    'v1': 2,
    'v9': 2,
    'vanessa': 1,
    'vari': 0,
    've': [0, 1, 2, 3],
    'version': 3,
    'via': 3,
    'victim': 2,
    'view': 2,
    'viewport': 3,
    'violenc': 2,
    'visibl': 2,
    'visit': 0,
    'visual': [0, 3],
    'wa': [1, 2],
    'wai': 0,
    'walk': 2,
    'water': 2,
    'wave': 2,
    'we': [0, 2, 3],
    'web': [0, 1],
    'websit': 0,
    'welcom': 2,
    'welsh': 1,
    'were': 2,
    'west': 2,
    'what': [1, 2, 3],
    'wheel': 2,
    'where': [2, 3],
    'which': [0, 3],
    'wide': 1,
    'width': 3,
    'wildcard': 3,
    'within': [1, 3],
    'won': [1, 2, 3],
    'work': [0, 1, 2, 3],
    'world': [1, 2, 3],
    'wrap': 2,
    'write': [1, 2],
    'www': 2,
    'x': 2,
    'y': 2,
    'year': 2,
    'yeogurt': 2,
    'yeoman': [],
    'you': [0, 1, 2, 3],
    'your': [0, 2, 3],
    'z': 2,
    'zero': 2,
    'zoom': 2,
  },
  titles: [
    '<span class="section-number">4. </span>Framework',
    'First Visual Story',
    '<span class="section-number">9. </span>Map',
    '<span class="section-number">5. </span>Template',
  ],
  titleterms: {
    about: 1,
    content: 1,
    edit: 3,
    first: 1,
    framework: 0,
    github: [],
    index: 3,
    instal: 0,
    map: 2,
    our: 0,
    push: [],
    section: [0, 3],
    server: 0,
    start: 0,
    stori: 1,
    system: 0,
    tabl: 1,
    templat: 3,
    test: 0,
    visual: 1,
    what: 0,
  },
});
