name: Deploy demonstration

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: demo
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci --production

      - name: Build distribution
        run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: release-candidate
          path: demo/_dist

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-candidate
          path: _dist

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _dist

      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
